# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import emails.email_utility


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_emailsource_sentdatetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsource',
            old_name='template',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='emailsource',
            name='specificData',
            field=models.TextField(validators=[emails.email_utility.csv_validator]),
        ),
    ]
